DROP FUNCTION IF EXISTS public.party_get_state(UUID, UUID);
DROP FUNCTION IF EXISTS public.party_get_by_character(UUID, TEXT);
DROP FUNCTION IF EXISTS public.party_create(UUID, UUID, TEXT);
DROP FUNCTION IF EXISTS public.party_add_member(UUID, UUID, TEXT, UUID, TEXT);
DROP FUNCTION IF EXISTS public.party_remove_member(UUID, UUID, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.party_change_leader(UUID, UUID, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.party_disband(UUID, UUID, TEXT);

ALTER TABLE Party
    ADD COLUMN IF NOT EXISTS PartyName VARCHAR(64),
    ADD COLUMN IF NOT EXISTS PartyDescription TEXT,
    ADD COLUMN IF NOT EXISTS PublicJoinEnabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS ExpDistributionMode SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS LootDistributionMode SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS MaxMembers INT NOT NULL DEFAULT 8,
    ADD COLUMN IF NOT EXISTS IsTemporary BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS CreatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS DisbandedAt TIMESTAMPTZ;

ALTER TABLE PartyMember
    ADD COLUMN IF NOT EXISTS PartyRole SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS MapColor VARCHAR(16),
    ADD COLUMN IF NOT EXISTS JoinedAt TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE PartyMember
SET PartyRole = CASE WHEN PartyLeader THEN 2 ELSE 0 END;

CREATE UNIQUE INDEX IF NOT EXISTS ux_party_customerguid_partyguid
    ON Party (CustomerGUID, PartyGuid);

CREATE UNIQUE INDEX IF NOT EXISTS ux_party_customerguid_partyname_active
    ON Party (CustomerGUID, LOWER(PartyName))
    WHERE PartyName IS NOT NULL AND DisbandedAt IS NULL;

DELETE FROM PartyMember pm
WHERE NOT EXISTS (
    SELECT 1
    FROM Characters c
    WHERE c.CustomerGUID = pm.CustomerGUID
        AND c.CharacterID = pm.CharacterID
);

DELETE FROM Party p
WHERE NOT EXISTS (
    SELECT 1
    FROM PartyMember pm
    WHERE pm.CustomerGUID = p.CustomerGUID
        AND pm.PartyID = p.PartyID
);
