version: "3.7"

services:
  ### Microsoft SQL Database
  mssql:
    build:
      context: mssql/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer # Developer, Express, Standard, Enterprise, EnterpriseCore
      - SA_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-data:/var/opt/mssql/log
      - mssql-data:/var/opt/mssql/secrets
    container_name: MSSQL

  ### PostgreSQL Database
  postgres:
    build:
      context: postgres/
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: PostgreSQL

  ### MySql Database
  mysql:
    build:
      context: mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: MySql

volumes:
  mssql-data:
  postgres-data:
  mysql-data:
